InstituoEnsinoSuperior/Controllers/DepartamentoController.cs
using InstituoEnsinoSuperior.Data;
using Microsoft.AspNetCore.Mvc;
using System.Linq;
using System;
using InstituoEnsinoSuperior.Models;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InstituoEnsinoSuperior.Controllers
{
    public class DepartamentoController : Controller
    {
        private readonly IESContext _context;

        //Contrutor para injeção de dependência
        public DepartamentoController(IESContext context)
        {
            this._context = context;
        }

        //Método para listar os departamentos 
        public async  Task<IActionResult> Index()
        {
            //Implentação tardia,(Sem associação)
            //List<Departamento> departamentos = await _context.Departamentos.ToListAsync();

            //Nova implementação, incluindo a instituição com retorno ordenado por nome
            var departamentos = await _context.Departamentos.Include(i => i.Instituicao).OrderBy(x => x.Nome).ToListAsync();
            return View(departamentos);
        }

        //Método para View da criação do departamento 
        public async Task<IActionResult> Create()
        {
            //Vai pegar o nome da instituição no banco de dados
            var instituicoes = await _context.Instituicoes.OrderBy(x => x.Nome).ToListAsync();
            //Depois, um objeto é inserido na coleção, logo no início,realocando os demais. Isso é feito para que uma mensagem orientativa seja exibida ao  usuário no DropDownList
            instituicoes.Insert(0, new Instituicao() { InstituicaoId = 0, Nome = "selecione uma instituição" });
            //Vai ser armazenado na ViewBag para ser usada no front
            ViewBag.Instituicoes = instituicoes;
            return View();
        }

        //Método para criação do departamento no banco de dados 
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(Departamento departamento)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    _context.Add(departamento);
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index));
                }
            }
            catch (DbUpdateException)
            {
                ModelState.AddModelError("", "Não foi possível inserir os dados.");
            }
            return View(departamento);
        }

        //Método para view de edição 
        public async Task<IActionResult> Edit (long? id)
        {
            //Vai verificar se foi passado algum Id 
            if(id == null)
            {
                return NotFound();
            }
            //Vai verificar no banco de dados o id que foi passado
            var departamento = await _context.Departamentos.SingleOrDefaultAsync(x => x.DepartamentoId == id);
            if (departamento == null)
            {
                return NotFound();
            }
            //Vai armazenar na viewBang
            ViewBag.Instituicoes = new SelectList(_context.Instituicoes.OrderBy(x => x.Nome), "InstituicaoId", "Nome", departamento.InstituicaoId);
            //Se tiver tudo certo vai retornar o departamento 
            return View(departamento);
        }

        //Método para Edição do departamento
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(Departamento departamento, long? id)
        {
            //Vai verificar se o id é igual ao que foi passado
            if (id !=   departamento.DepartamentoId) 
            {
                return NotFound();
            }
            //Verifica se foi passado algo na view
            if (ModelState.IsValid) { 
            _context.Departamentos.Update(departamento);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
            }

            return View(departamento);
        }

        //Método para detalhes do departamento
        public async Task<IActionResult> Details(long? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            //var departamento = await _context.Departamentos.SingleOrDefaultAsync(x => x.DepartamentoId == id);
            var departamento = await _context.Departamentos.Include(i => i.Instituicao).OrderBy(x => x.Nome).SingleOrDefaultAsync(x => x.DepartamentoId == id);
            if(departamento == null)
            {
                return NotFound();
            }
            return View(departamento);
        }

        //Método para view de remoção
        public async Task<IActionResult> Delete(long? id)
        {
            if(id == null)
            {
                return NotFound();
            }
            var departameto = await _context.Departamentos.SingleOrDefaultAsync(x => x.DepartamentoId == id);
            if (departameto == null)
            {
                return NotFound();
            }
            return View(departameto);
        }

        //Método para deletar o departamento
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirm(long? id) 
        {
            if (id == null)
            {
                return NotFound();
            }
            var departameto = await _context.Departamentos.SingleOrDefaultAsync(x => x.DepartamentoId == id);
            if (departameto == null)
            {
                return NotFound();
            }
            _context.Departamentos.Remove(departameto);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }



    }
}

InstituoEnsinoSuperior/Controllers/InstituicaoController.cs
using InstituoEnsinoSuperior.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Linq;
using InstituoEnsinoSuperior.Data;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace InstituoEnsinoSuperior.Controllers
{
    public class InstituicaoController : Controller
    {
        private readonly IESContext _context;

        public InstituicaoController(IESContext context)
        {
            this._context = context;
        }

        // Definição de uma action chamada Index
        //Vai listar as instituições 
        public async Task<IActionResult> Index()
        {
            //Vai retornar as instituições por ordem alfabetica
            List<Instituicao> instituicoes = await _context.Instituicoes.OrderBy(x => x.Nome).ToListAsync();

            return View(instituicoes);
        }

        //Para pagina de criação(interação) de uma nova instituição, interação com usuário
        public ActionResult Create()
        {
            return View();
        }

        //Método para ciração de uma nova instituição utilizando os dados recebido pela view
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async  Task<ActionResult> Create(Instituicao instituicao)//Vai receber da View os parâmetros (nome, endereço)
        {
            if (ModelState.IsValid)
            {
                //Vai adicionar a instituição 
                _context.Instituicoes.Add(instituicao);
                await _context.SaveChangesAsync();
                //Vai redirecionar para página Index
                return RedirectToAction(nameof(Index));
            }
            return View(instituicao);
        }

        //Método para interação da tela de edição da instituição com o usuário(vai mostrar a instituição pelo Id)
        public async Task<ActionResult> Edit(long? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            //Vai receber o id passado pela view para pegar a instituição e retornar na view
            return View(await _context.Instituicoes.SingleOrDefaultAsync(i => i.InstituicaoId == id));
        }

        //Método que vai fazer a alteração dos dados
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<ActionResult> Edit(Instituicao instituicao, long? id)
        {
            //Vai verificar se o id é igual ao que foi passado
            if (id != instituicao.InstituicaoId)
            {
                return NotFound();
            }
           
            if(ModelState.IsValid)
            {
                //Vai Atualizar a instituição editada
                _context.Instituicoes.Update(instituicao);
                await _context.SaveChangesAsync();
                //Vai redirecionar a página 
                return RedirectToAction(nameof(Index));
            }
            return View(instituicao);
        }
        
        //Método para mostrar o detalhe da instituição 
        public async Task<ActionResult> Details (long id)
        {
            var instituicoes = await _context.Instituicoes.Include(i => i.Departamentos).SingleOrDefaultAsync(x => x.InstituicaoId == id);
            return View(instituicoes);
        }

        //Método para tela de interação delete da instituição
        public async Task<ActionResult> Delete (long id)
        {
            return View(await _context.Instituicoes.SingleOrDefaultAsync(i => i.InstituicaoId == id));
        }

        //Método para a deletar a instituição do sistema
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete (Instituicao instituto){
             _context.Instituicoes.Remove(instituto);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

InstituoEnsinoSuperior/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InstituoEnsinoSuperior</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">InstituoEnsinoSuperior</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2021 - InstituoEnsinoSuperior</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

InstituoEnsinoSuperior/Views/Shared/_LayoutIES.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - InstituoEnsinoSuperior</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>


</head>

<body>
    <nav class="navbar navbar-dark bg-primary navbar-fixed-top">
        <div class="container-fluid">
            <div class="row">
                <div class="navbar-header">

                </div>
                <div>
                    <ul class="nav navbar-nav navbar-dark">
                        <li class="navbar-brand">&nbsp;&nbsp;&nbsp;ASP.NET Core MVC</li>
                    </ul>
                </div>
            </div>
        </div>
    </nav>
    <partial name="_CookieConsentPartial" />

    <div class="container" style="margin-top:20px;">
        <div class="row">
            <div class="col-2">
                <nav class="nav flex-column bg-transparent" style="margin-left:40px;">
                    <div class="row">
                        <a class="nav-link active" asp-controller="Instituicao" asp-action="Index">Intituições</a>
                    </div>
                    <div class="row">
                        <a class="nav-link"  asp-controller="Departamento" asp-action="Index">Departamentos</a>
                    </div>
                </nav>
            </div>
            <div class="col-10">
                @RenderBody();
            </div>
        </div>
    </div>

    <nav class="navbar fixed-bottom" style="background-color:#e3f2fd; margin-top:20px;">
        <a class="navbar-brand" href="#">Eduardo Cavalcanti</a>
    </nav>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.6.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/5.0.2/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>
    @RenderSection("Scripts", required: false)

</body>
</html>